import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Card/Card'
import Grid from '../components/Grid/Grid'
import { CardInterface } from '../interface/Card.interface'
import styles from '../styles/Home.module.scss'

const data: CardInterface[]= [{
  title: 'Documentation',
  description: 'Find in-depth information about Next.js features and API.',
  link: 'https://nextjs.org/docs',
  id: 1
},
{
  title: 'Learn',
  description: 'Learn about Next.js in an interactive course with quizzes!',
  link: 'https://nextjs.org/learn',
  id: 2
},
{
  title: 'Examples',
  description: 'Discover and deploy boilerplate example Next.js projects.',
  link: 'https://nextjs.org/examples',
  id: 3
}]

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <Grid>
          {data.map((item, index) => (
            <Card key={index} {...item} />
          ))}
        </Grid>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
