import type { NextPage } from "next";
import Head from "next/head";

import NavBar from "../components/NavBar/NavBar";
import Card from "../components/Landing/Card/Card";
import Grid from "../components/Landing/Grid/Grid";

import styles from "../styles/Home.module.scss";

import data from "../assets/blog.json";

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar></NavBar>
      <div className={styles.container}>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          {/* <Grid>
            {data.data.map((item, index) => (
              <Card key={index} {...item} />
            ))}
          </Grid> */}
        </main>
      </div>
    </div>
  );
};

export default Home;
